# Generated by Django 3.2 on 2022-10-25 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('points', models.PositiveIntegerField(max_length=3)),
                ('price', models.PositiveIntegerField(max_length=3)),
                ('province', models.CharField(max_length=50)),
                ('taster_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('winery', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
